// Tests for tools/lib/planning-index.js — the auto-generated `/sig:index`
// generator (M5.E3.S2 / FR3). Built up task by task:
//   t2 — enumeratePlanningDocs: mechanical doc catalog (path, tier, growth-policy)
//   t3 — parseExistingAnnotations: round-trip curated notes by key (two keyspaces + legend)
//   t4 — renderPlanningIndex / regeneratePlanningIndex: idempotent, parse↔render fixpoint

import { describe, it, expect, beforeEach, afterEach } from 'vitest';
import { mkdtemp, rm, mkdir, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';

import { readFile } from 'node:fs/promises';

import { ROOT } from '../tools/lib/roster.js';
import {
  enumeratePlanningDocs,
  parseExistingAnnotations,
  renderPlanningIndex,
  regeneratePlanningIndex,
  buildDecisionIdMap,
  resolveDecisionId,
} from '../tools/lib/planning-index.js';

// A representative INDEX in the generator's canonical format — the shape t4's
// renderPlanningIndex emits. Used to prove parse recovers curated notes by key
// across the two keyspaces (file-path + Epic-ID) plus the tier legend.
const SAMPLE_INDEX = `# Signal — \`.planning/\` Documentation Map

> Auto-generated by \`/sig:index\`. Mechanical rows regenerate from disk; curated
> notes after each \` — \` survive by key.

**Tier legend:**
- 🔥 **LIVE** — the working set + append-logs.
- 🧊 **COLD** — closed work: archived scaffolding + per-Epic retrospectives.

---

## Live — working set

- [DECISIONS.md](DECISIONS.md) — \`append-log\` — Decision log; grep by \`D-…\` ID, don't load whole.
- [PROJECT.md](PROJECT.md) — \`other\` — v1 spec + locked vocabulary.
  **Gotcha:** ID-is-identity rule (Milestone/Epic/Slice/Task are fixed terms).
- [BUGS.md](BUGS.md) — \`other\` — _(note pending)_

## Cold — archived + retrospectives

- [M4.5.E1-RETROSPECTIVE.md](M4.5.E1-RETROSPECTIVE.md) — \`other\` — _(note pending)_
- [archive/M4.5/E1/M4.5.E1-PLAN.md](archive/M4.5/E1/M4.5.E1-PLAN.md) — \`other\` — _(note pending)_

## Epic ledger

- [M4.5.E1](M4.5.E1-RETROSPECTIVE.md) — Marketplace install-path fix (Slices 3–5 shelved).
- [M4.5.E10](M4.5.E10-RETROSPECTIVE.md) — _(note pending)_
`;

async function seedPlanning(base) {
  const p = join(base, '.planning');
  await mkdir(join(p, 'archive', 'M4.5', 'E1'), { recursive: true });
  await writeFile(join(p, 'PROJECT.md'), '# project\n', 'utf-8');
  await writeFile(join(p, 'DECISIONS.md'), '# decisions\n', 'utf-8');
  await writeFile(join(p, 'MILESTONE-5.md'), '# milestone\n', 'utf-8');
  await writeFile(join(p, 'M4.5.E1-RETROSPECTIVE.md'), '# retro\n', 'utf-8');
  await writeFile(join(p, 'RETROSPECTIVES.md'), '# retro index\n', 'utf-8');
  await writeFile(join(p, 'archive', 'M4.5', 'E1', 'M4.5.E1-PLAN.md'), '# archived plan\n', 'utf-8');
}

describe('enumeratePlanningDocs (t2) — mechanical doc catalog', () => {
  let base;
  beforeEach(async () => {
    base = await mkdtemp(join(tmpdir(), 'planning-index-'));
    await seedPlanning(base);
  });
  afterEach(async () => {
    await rm(base, { recursive: true, force: true });
  });

  it('enumerates every .md doc under .planning/ (incl. archive), sorted by path', async () => {
    const docs = await enumeratePlanningDocs(base);
    const paths = docs.map((d) => d.path);
    expect(paths).toEqual([
      '.planning/DECISIONS.md',
      '.planning/M4.5.E1-RETROSPECTIVE.md',
      '.planning/MILESTONE-5.md',
      '.planning/PROJECT.md',
      '.planning/RETROSPECTIVES.md',
      '.planning/archive/M4.5/E1/M4.5.E1-PLAN.md',
    ]);
  });

  it('classifies COLD = under archive/ OR *-RETROSPECTIVE.md; everything else non-COLD', async () => {
    const docs = await enumeratePlanningDocs(base);
    const tier = Object.fromEntries(docs.map((d) => [d.path, d.tier]));
    expect(tier['.planning/M4.5.E1-RETROSPECTIVE.md']).toBe('COLD'); // retrospective
    expect(tier['.planning/archive/M4.5/E1/M4.5.E1-PLAN.md']).toBe('COLD'); // under archive/
    expect(tier['.planning/RETROSPECTIVES.md']).toBe('LIVE'); // the INDEX append-log, NOT a *-RETROSPECTIVE.md
    expect(tier['.planning/DECISIONS.md']).toBe('LIVE');
    expect(tier['.planning/PROJECT.md']).toBe('LIVE');
  });

  it('carries the growth-policy (classifyDocGrowthPolicy) + byte size per doc', async () => {
    const docs = await enumeratePlanningDocs(base);
    const gp = Object.fromEntries(docs.map((d) => [d.path, d.growthPolicy]));
    expect(gp['.planning/DECISIONS.md']).toBe('append-log');
    expect(gp['.planning/RETROSPECTIVES.md']).toBe('append-log');
    expect(gp['.planning/MILESTONE-5.md']).toBe('milestone');
    expect(gp['.planning/PROJECT.md']).toBe('other');
    for (const d of docs) expect(typeof d.bytes).toBe('number');
  });

  it('returns [] when .planning/ is absent (no throw)', async () => {
    const empty = await mkdtemp(join(tmpdir(), 'planning-index-empty-'));
    expect(await enumeratePlanningDocs(empty)).toEqual([]);
    await rm(empty, { recursive: true, force: true });
  });
});

describe('relative baseDir (B18: path-relativize, not slice)', () => {
  // B18: `full.slice(baseDir.length + 1)` corrupts keys when baseDir='.' —
  // `join('.', '.planning')` normalizes `./` away → slice(2) chops '.p', yielding
  // 'lanning/BACKLOG.md'. That also breaks the INDEX self-skip ('lanning/INDEX.md'
  // never equals the '.planning/INDEX.md' sentinel, so INDEX lists itself).
  let base;
  let origCwd;
  afterEach(async () => {
    if (origCwd) {
      process.chdir(origCwd);
      origCwd = undefined;
    }
    if (base) {
      await rm(base, { recursive: true, force: true });
      base = undefined;
    }
  });

  it("enumeratePlanningDocs('.') roots keys at .planning/ and self-skips INDEX.md", async () => {
    base = await mkdtemp(join(tmpdir(), 'planning-index-dot-'));
    const p = join(base, '.planning');
    await mkdir(p, { recursive: true });
    await writeFile(join(p, 'BACKLOG.md'), '# backlog\n', 'utf-8');
    await writeFile(join(p, 'PROJECT.md'), '# project\n', 'utf-8');
    await writeFile(join(p, 'INDEX.md'), '# index\n', 'utf-8');

    origCwd = process.cwd();
    process.chdir(base);

    const docs = await enumeratePlanningDocs('.');
    const paths = docs.map((d) => d.path);
    expect(paths).toContain('.planning/BACKLOG.md'); // NOT 'lanning/BACKLOG.md'
    expect(paths.every((p) => p.startsWith('.planning/'))).toBe(true);
    // Self-skip survives a relative baseDir: INDEX.md must not list itself.
    expect(paths.some((p) => p.endsWith('INDEX.md'))).toBe(false);
  });

  it("resolveDecisionId('.', id) resolves to a .planning/-rooted home", async () => {
    base = await mkdtemp(join(tmpdir(), 'decision-map-dot-'));
    const p = join(base, '.planning');
    await mkdir(p, { recursive: true });
    await writeFile(join(p, 'DECISIONS.md'), '## 2026-07-18 — d\n\n- D-CUR-2 second\n', 'utf-8');

    origCwd = process.cwd();
    process.chdir(base);

    expect(await resolveDecisionId('.', 'D-CUR-2')).toBe('.planning/DECISIONS.md');
  });
});

describe('parseExistingAnnotations (t3) — round-trip curated notes by key', () => {
  it('recovers file-path notes (the byPath keyspace)', () => {
    const a = parseExistingAnnotations(SAMPLE_INDEX);
    expect(a.byPath['DECISIONS.md']).toBe("Decision log; grep by `D-…` ID, don't load whole.");
  });

  it('recovers a multi-line curated Gotcha note (continuation lines survive)', () => {
    const a = parseExistingAnnotations(SAMPLE_INDEX);
    expect(a.byPath['PROJECT.md']).toContain('v1 spec + locked vocabulary.');
    expect(a.byPath['PROJECT.md']).toContain('**Gotcha:** ID-is-identity rule');
  });

  it('recovers Epic-ID ledger notes (the byEpic keyspace) — no collision with path rows', () => {
    const a = parseExistingAnnotations(SAMPLE_INDEX);
    expect(a.byEpic['M4.5.E1']).toBe('Marketplace install-path fix (Slices 3–5 shelved).');
    // The Cold path-row for M4.5.E1-RETROSPECTIVE.md must NOT leak into byEpic.
    expect(a.byPath['M4.5.E1-RETROSPECTIVE.md']).toBeUndefined(); // placeholder → not stored
  });

  it('captures the tier legend by heading', () => {
    const a = parseExistingAnnotations(SAMPLE_INDEX);
    expect(a.legend).toContain('🔥 **LIVE**');
    expect(a.legend).toContain('🧊 **COLD**');
  });

  it('treats the placeholder as "no annotation" (so absent notes stay unset)', () => {
    const a = parseExistingAnnotations(SAMPLE_INDEX);
    expect(a.byPath['BUGS.md']).toBeUndefined();
    expect(a.byEpic['M4.5.E10']).toBeUndefined();
  });

  it('empty / null content → empty keyspaces + null legend (no throw)', () => {
    expect(parseExistingAnnotations('')).toEqual({ byPath: {}, byEpic: {}, legend: null });
    expect(parseExistingAnnotations(null)).toEqual({ byPath: {}, byEpic: {}, legend: null });
  });
});

describe('renderPlanningIndex + regeneratePlanningIndex (t4) — idempotent, fixpoint', () => {
  let base;
  beforeEach(async () => {
    base = await mkdtemp(join(tmpdir(), 'planning-index-render-'));
    await seedPlanning(base);
  });
  afterEach(async () => {
    await rm(base, { recursive: true, force: true });
  });

  it('the generated INDEX.md never lists itself (idempotency guard)', async () => {
    await regeneratePlanningIndex(base);
    const docs = await enumeratePlanningDocs(base);
    expect(docs.some((d) => d.path === '.planning/INDEX.md')).toBe(false);
  });

  it('renders mechanical rows split by tier + an Epic ledger, sorted by path', async () => {
    const docs = await enumeratePlanningDocs(base);
    const content = renderPlanningIndex(docs, { byPath: {}, byEpic: {}, legend: null });
    expect(content).toContain('## Live — working set');
    expect(content).toContain('## Cold — archived + retrospectives');
    expect(content).toContain('## Epic ledger');
    expect(content).toContain('- [DECISIONS.md](DECISIONS.md) — `append-log` —');
    expect(content).toContain('- [archive/M4.5/E1/M4.5.E1-PLAN.md](archive/M4.5/E1/M4.5.E1-PLAN.md) — `other` —');
    expect(content).toContain('- [M4.5.E1](M4.5.E1-RETROSPECTIVE.md) —'); // ledger row
  });

  it('emits the placeholder for an absent note; re-attaches a curated note by key', async () => {
    const docs = await enumeratePlanningDocs(base);
    const content = renderPlanningIndex(docs, {
      byPath: { 'DECISIONS.md': 'grep by ID, do not load whole.' },
      byEpic: {},
      legend: null,
    });
    expect(content).toContain('- [DECISIONS.md](DECISIONS.md) — `append-log` — grep by ID, do not load whole.');
    expect(content).toContain('- [PROJECT.md](PROJECT.md) — `other` — _(note pending)_');
  });

  it('GATE (a): a no-op regeneration returns {written:false} and produces no diff', async () => {
    const first = await regeneratePlanningIndex(base);
    expect(first.written).toBe(true);
    const before = await readFile(join(base, '.planning', 'INDEX.md'), 'utf-8');
    const second = await regeneratePlanningIndex(base);
    expect(second.written).toBe(false);
    const after = await readFile(join(base, '.planning', 'INDEX.md'), 'utf-8');
    expect(after).toBe(before);
  });

  it('GATE (b): parse↔render fixpoint — render(parse(render(x))) === render(x)', async () => {
    const docs = await enumeratePlanningDocs(base);
    const x = renderPlanningIndex(docs, {
      byPath: { 'PROJECT.md': 'v1 spec.\n  **Gotcha:** ID-is-identity rule.' },
      byEpic: { 'M4.5.E1': 'Marketplace install-path fix.' },
      legend: null,
    });
    const y = renderPlanningIndex(docs, parseExistingAnnotations(x));
    expect(y).toBe(x);
  });

  it('AC3.2: a curated note survives a regeneration that adds an unrelated doc', async () => {
    await regeneratePlanningIndex(base); // initial
    // Hand-curate a note into the DECISIONS row.
    const indexPath = join(base, '.planning', 'INDEX.md');
    let content = await readFile(indexPath, 'utf-8');
    content = content.replace(
      '- [DECISIONS.md](DECISIONS.md) — `append-log` — _(note pending)_',
      '- [DECISIONS.md](DECISIONS.md) — `append-log` — Curated: grep by `D-…` ID.',
    );
    await writeFile(indexPath, content, 'utf-8');
    // Add an unrelated doc → forces a regen that changes other rows.
    await writeFile(join(base, '.planning', 'OPEN-QUESTIONS.md'), '# q\n', 'utf-8');
    const res = await regeneratePlanningIndex(base);
    expect(res.written).toBe(true);
    const after = await readFile(indexPath, 'utf-8');
    expect(after).toContain('- [DECISIONS.md](DECISIONS.md) — `append-log` — Curated: grep by `D-…` ID.');
    expect(after).toContain('- [OPEN-QUESTIONS.md](OPEN-QUESTIONS.md) —');
  });
});

describe('D-ID → home map + resolveDecisionId (t5) — AC3.3', () => {
  let base;
  beforeEach(async () => {
    base = await mkdtemp(join(tmpdir(), 'decision-map-'));
    await mkdir(join(base, '.planning', 'archive', 'M1'), { recursive: true });
    await writeFile(
      join(base, '.planning', 'DECISIONS.md'),
      '## 2026-07-18 — current\n\n- D-CUR-1 first\n- D-CUR-2 second\n- D-CUR-3 third\n',
      'utf-8',
    );
    await writeFile(
      join(base, '.planning', 'archive', 'M1', 'DECISIONS.md'),
      '## 2026-04-22 — old\n\n- D-OLD-1 (a) and D-OLD-2 (b)\n',
      'utf-8',
    );
  });
  afterEach(async () => {
    await rm(base, { recursive: true, force: true });
  });

  it('buildDecisionIdMap keys sourceFile → ID-prefix ranges (live + archive)', async () => {
    const map = await buildDecisionIdMap(base);
    expect(map['.planning/DECISIONS.md'].CUR).toEqual({ min: 1, max: 3 });
    expect(map['.planning/archive/M1/DECISIONS.md'].OLD).toEqual({ min: 1, max: 2 });
  });

  it('a live D-… resolves to the live DECISIONS.md', async () => {
    expect(await resolveDecisionId(base, 'D-CUR-2')).toBe('.planning/DECISIONS.md');
  });

  it("an archived block's D-… resolves to its archive file (AC3.3 archived home)", async () => {
    expect(await resolveDecisionId(base, 'D-OLD-1')).toBe('.planning/archive/M1/DECISIONS.md');
    expect(await resolveDecisionId(base, 'D-OLD-2')).toBe('.planning/archive/M1/DECISIONS.md');
  });

  it('an unknown D-… resolves to null (not resolvable)', async () => {
    expect(await resolveDecisionId(base, 'D-NOPE-9')).toBeNull();
  });

  it('mechanical-fresh: self-heals when an archive DECISIONS.md appears after first call', async () => {
    // Remove the archive file, prove D-OLD-1 is unresolvable, then re-create it.
    await rm(join(base, '.planning', 'archive', 'M1', 'DECISIONS.md'));
    expect(await resolveDecisionId(base, 'D-OLD-1')).toBeNull();
    await writeFile(
      join(base, '.planning', 'archive', 'M1', 'DECISIONS.md'),
      '- D-OLD-1 revived\n',
      'utf-8',
    );
    // No cache — the next call rebuilds from disk and finds it.
    expect(await resolveDecisionId(base, 'D-OLD-1')).toBe('.planning/archive/M1/DECISIONS.md');
  });

  it('every D-… across Signal\'s live + archived DECISIONS resolves to a file that DEFINES it (AC3.3 on real data)', async () => {
    // Post-v3-migrate reality: decision homes are split across the live
    // DECISIONS.md and the per-milestone archives (FR5 eviction). The invariant
    // that must hold on real data is anchor-resolvability: every `D-…` resolves to
    // a DECISIONS file that actually defines it (a heading- or bold-lead
    // `D-<id> —`), never merely references it — the guarantee FR5's fail-closed
    // anchor gate depends on. (Pre-migrate this was "all resolve to live"; the
    // Signal dogfood split the homes.)
    const files = [
      '.planning/DECISIONS.md',
      '.planning/archive/milestones/DECISIONS.md',
      '.planning/archive/M4.5/DECISIONS.md',
    ];
    const ids = new Set();
    const defines = (content, id) => {
      const esc = id.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
      return new RegExp(String.raw`(?:^#{2,6}\s+|\*\*)${esc}\s*[—–-]`, 'm').test(content);
    };
    for (const f of files) {
      const c = await readFile(join(ROOT, f), 'utf-8');
      for (const m of c.matchAll(/\bD-[A-Za-z0-9]+-\d+\b/g)) ids.add(m[0]);
    }
    expect(ids.size).toBeGreaterThan(50); // sanity: the log has many D-IDs
    const unresolved = [];
    for (const id of ids) {
      const home = await resolveDecisionId(ROOT, id);
      if (!home) {
        unresolved.push(`${id} → null`);
        continue;
      }
      const c = await readFile(join(ROOT, home), 'utf-8');
      if (!defines(c, id)) unresolved.push(`${id} → ${home} (does not define it)`);
    }
    expect(unresolved).toEqual([]);
  });

  it('an evicted id DEFINED in the archive but REFERENCED in the live file resolves to the archive (definition beats reference — D-v016-2 dogfood regression)', async () => {
    // Post-eviction reality: the archive DEFINES D-EV-2 (a heading-lead — the
    // shape DECISIONS.md uses to introduce a decision); the live file only
    // REFERENCES it in prose in a later, still-live section. Range-membership
    // alone TIES (both files carry a D-EV range covering 2). The definition must
    // win — else a bare live mention out-votes the archive that actually documents
    // the decision, and FR5's fail-closed anchor gate refuses the whole eviction
    // (this is exactly the D-v016-2 case the Signal dogfood surfaced).
    await writeFile(
      join(base, '.planning', 'archive', 'M1', 'DECISIONS.md'),
      '## 2026-04-22 — old\n\n### D-EV-1 — first\n\nbody\n\n### D-EV-2 — second\n\nbody\n',
      'utf-8',
    );
    await writeFile(
      join(base, '.planning', 'DECISIONS.md'),
      '## 2026-07-18 — current\n\n**D-CUR-1 — a.** Consistent with the earlier D-EV-2 and D-EV-1 (bare references).\n',
      'utf-8',
    );
    expect(await resolveDecisionId(base, 'D-EV-2')).toBe('.planning/archive/M1/DECISIONS.md');
  });
});
