import { describe, it, expect } from 'vitest';
import { countMarkers, appendNote } from '../tools/lib/walkthrough.js';

describe('countMarkers', () => {
  it('returns zeros for null content', () => {
    expect(countMarkers(null)).toEqual({ inferred: 0, fillIn: 0, total: 0 });
  });

  it('returns zeros for empty content', () => {
    expect(countMarkers('')).toEqual({ inferred: 0, fillIn: 0, total: 0 });
  });

  it('returns zeros when no markers are present', () => {
    const content = '# Project\n\nVision: build a thing.\n';
    expect(countMarkers(content)).toEqual({ inferred: 0, fillIn: 0, total: 0 });
  });

  it('counts a single [INFERRED — please verify] marker', () => {
    const content = '## Vision\n\nA thing.\n\n`[INFERRED — please verify]`\n';
    expect(countMarkers(content)).toEqual({ inferred: 1, fillIn: 0, total: 1 });
  });

  it('counts a single [FILL IN — reason] marker', () => {
    const content = '## Done When\n\n`[FILL IN — what does done look like?]`\n';
    expect(countMarkers(content)).toEqual({ inferred: 0, fillIn: 1, total: 1 });
  });

  it('counts multiple markers of both kinds', () => {
    const content = `# Project

## Vision

A thing.

\`[INFERRED — please verify]\`

## Problem

\`[INFERRED — please verify]\`

## Done When

\`[FILL IN — what's the next concrete milestone?]\`

## Constraints

- **Deployment target:** \`[FILL IN — where does this deploy?]\`
- **Hard constraints not in code:** \`[FILL IN — anything else?]\`
`;
    expect(countMarkers(content)).toEqual({
      inferred: 2,
      fillIn: 3,
      total: 5,
    });
  });

  it('does not count bare [INFERRED] / [FILL IN] prose references', () => {
    const content = `> Every \`[INFERRED]\` and \`[FILL IN]\` marker is your responsibility to resolve.
> Do this before /sig:calibrate.
`;
    expect(countMarkers(content)).toEqual({ inferred: 0, fillIn: 0, total: 0 });
  });

  it('counts confidence-labeled INFERRED markers (LANDSCAPE.md style)', () => {
    const content = `## What this project is

A web service. \`[INFERRED — high confidence]\`

Probably has auth. \`[INFERRED — low confidence]\`
`;
    expect(countMarkers(content)).toEqual({ inferred: 2, fillIn: 0, total: 2 });
  });

  it('counts markers that are not backtick-wrapped', () => {
    // Real PROJECT.md template wraps in backticks but the regex shouldn't
    // depend on backticks — robust against minor template drift.
    const content = '## Vision\n\nA thing. [INFERRED — please verify]\n';
    expect(countMarkers(content)).toEqual({ inferred: 1, fillIn: 0, total: 1 });
  });
});

describe('appendNote', () => {
  it('returns unchanged for null content', () => {
    expect(appendNote(null, 'note')).toBeNull();
  });

  it('returns unchanged for empty note', () => {
    const content = '## Notes\n\n- existing\n';
    expect(appendNote(content, '')).toBe(content);
    expect(appendNote(content, '   ')).toBe(content);
  });

  it('appends to an existing populated ## Notes section', () => {
    const content = `# Project

## Vision

A thing.

## Notes

- Generated by /sig:init on 2026-04-27.
- Source signals: see scan files.
`;
    const result = appendNote(content, 'Deferred at /sig:init walkthrough on 2026-04-27: Vision.');
    expect(result).toBe(`# Project

## Vision

A thing.

## Notes

- Generated by /sig:init on 2026-04-27.
- Source signals: see scan files.
- Deferred at /sig:init walkthrough on 2026-04-27: Vision.
`);
  });

  it('preserves trailing newline conventions when appending', () => {
    const content = '## Notes\n\n- one\n- two\n';
    const result = appendNote(content, 'three');
    expect(result).toBe('## Notes\n\n- one\n- two\n- three\n');
  });

  it('appends to an empty ## Notes section (heading only)', () => {
    const content = '# Project\n\n## Notes\n';
    const result = appendNote(content, 'first note');
    expect(result).toBe('# Project\n\n## Notes\n\n- first note\n');
  });

  it('appends to a Notes section with blank-only body', () => {
    const content = '# Project\n\n## Notes\n\n\n';
    const result = appendNote(content, 'first note');
    expect(result).toBe('# Project\n\n## Notes\n\n- first note\n');
  });

  it('creates a ## Notes section if none exists', () => {
    const content = '# Project\n\n## Vision\n\nA thing.\n';
    const result = appendNote(content, 'a note');
    expect(result).toBe('# Project\n\n## Vision\n\nA thing.\n\n## Notes\n\n- a note\n');
  });

  it('creates a ## Notes section when content has no trailing newline', () => {
    const content = '# Project\n\nbody';
    const result = appendNote(content, 'a note');
    expect(result).toBe('# Project\n\nbody\n\n## Notes\n\n- a note\n');
  });

  it('inserts before the next h2 heading when ## Notes is not last', () => {
    // PROJECT.md template ends with ## Notes, but be robust in case a user
    // has added something below it (e.g., a manual ## Appendix).
    const content = `## Notes

- existing
- another

## Appendix

trailing material.
`;
    const result = appendNote(content, 'inserted');
    expect(result).toBe(`## Notes

- existing
- another
- inserted

## Appendix

trailing material.
`);
  });

  it('does not match h3 or deeper "Notes" headings', () => {
    const content = '# Project\n\n### Notes\n\n- internal note\n';
    const result = appendNote(content, 'top-level note');
    expect(result).toBe(
      '# Project\n\n### Notes\n\n- internal note\n\n## Notes\n\n- top-level note\n'
    );
  });

  it('trims whitespace around the supplied note', () => {
    const content = '## Notes\n\n- one\n';
    const result = appendNote(content, '   padded note   ');
    expect(result).toBe('## Notes\n\n- one\n- padded note\n');
  });

  it('handles multi-line notes by appending verbatim', () => {
    const content = '## Notes\n\n- one\n';
    const result = appendNote(content, 'first line\nsecond line');
    expect(result).toBe('## Notes\n\n- one\n- first line\nsecond line\n');
  });

  it('is idempotent in shape: appending twice yields two bullets', () => {
    let content = '## Notes\n\n- one\n';
    content = appendNote(content, 'two');
    content = appendNote(content, 'three');
    expect(content).toBe('## Notes\n\n- one\n- two\n- three\n');
  });
});
