// M6.E13 t7.1a — `work-migrate-v2.js` `migrateWorkStoreV2`: the v1 → v2
// migration, built aside and verified (AC8.1–AC8.3). See
// .planning/M6.E13-VALIDATION.md rows AC8.1, AC8.2, AC8.3 and PLAN Decisions
// 1, 10, 11.
//
// Dry run (default): the store AS IT IS NOW is converted, a v2 project is built
// in `outDir` (a copy of `.planning/` with the store swapped in), the manifest is
// verified, and the closes `confirmCloses` would confirm are PROBED against the
// source repo's `origin/<default>` — nothing in the source project changes.
//
// `--apply` runs only against temp git repos here: the live repository is
// migrated at t7.3, after Brett's go-ahead.

import { describe, it, expect, beforeEach, afterEach } from 'vitest';
import { mkdtempSync, mkdirSync, writeFileSync, readFileSync, existsSync, rmSync, realpathSync } from 'node:fs';
import { spawnSync } from 'node:child_process';
import { join, dirname } from 'node:path';
import { tmpdir } from 'node:os';

import { migrateWorkStoreV2, verifyConversion, convertStore } from '../plugin/tools/lib/work-migrate-v2.js';
import { stringifyItem } from '../plugin/tools/lib/work-item.js';
import { checkRecords, listRecords, storeVersion, recordPath, findDuplicateIds } from '../plugin/tools/lib/work-records.js';
import { snapshotTree } from './helpers/write-inventory.js';

const AT = '2026-09-01T00:00:00.000Z';
const NOW = '2026-10-04T12:00:00.000Z';
const by = 'b';

function g(cwd, ...args) {
  const r = spawnSync('git', ['-c', 'commit.gpgsign=false', '-c', 'user.email=t@t.co', '-c', 'user.name=T', ...args], {
    cwd,
    encoding: 'utf8',
  });
  if (r.status !== 0) throw new Error(`git ${args.join(' ')}: ${r.stderr}`);
  return r.stdout.trim();
}

function put(base, rel, content) {
  const p = join(base, rel);
  mkdirSync(dirname(p), { recursive: true });
  writeFileSync(p, content);
}

let root;
beforeEach(() => {
  root = realpathSync(mkdtempSync(join(tmpdir(), 'sig-migrate-v2-')));
});
afterEach(() => {
  rmSync(root, { recursive: true, force: true });
});

const item = (fields, body = 'Body.\n') => stringifyItem({ created: { at: AT, by }, ...fields }, body);

/**
 * A v1 store with one of every shape: inbox (N), backlog (T, with a pasted
 * legacy row, a status line and a relative link), a legacy close, a commit-proof
 * fixed close (→ close_requested), a no-commit fixed close named in
 * D-M6E13-20 (SIG-123 → legacy), a rejected close, a dup close, and an item in
 * an archived Epic folder beside the Epic's own documents.
 */
function v1Project(base, sha = 'abcdef1') {
  put(base, '.planning/work/WORK.md', '---\nkey: SIG\nschema_version: 1\n---\n\n# Work store\n\nv1 body text.\n');
  put(base, '.planning/work/WATCHLIST.md', '## Watchlist\n\n- one row\n');
  put(base, '.planning/PROJECT.md', '# Project\n');
  put(base, '.planning/work/inbox/SIG-1.md', item({ id: 'SIG-1', type: 'NEW', status: 'N', title: 'Raw capture' }));
  put(
    base,
    '.planning/work/backlog/SIG-2.md',
    item(
      { id: 'SIG-2', type: 'BUG', status: 'T', title: 'A bug', legacy_id: 'B2', priority: 'P2' },
      '| B2 | `confirmed` | P2 | The text of the bug, see [plan](../../PROJECT.md). |\n\n**Status:** confirmed\n',
    ),
  );
  put(
    base,
    '.planning/work/done/2026-09/SIG-3.md',
    item({ id: 'SIG-3', type: 'FEAT', status: 'C', title: 'Old', close: { reason: 'fixed', by, at: '2026-09-02', proof: 'legacy — not re-verified' } }),
  );
  put(
    base,
    '.planning/work/done/2026-09/SIG-4.md',
    item({ id: 'SIG-4', type: 'BUG', status: 'C', title: 'Fixed', close: { reason: 'fixed', by, at: '2026-09-03', proof: `commit ${sha} (v0.1.40) — tests/x.test.js` } }),
  );
  put(
    base,
    '.planning/work/done/2026-09/SIG-5.md',
    item({ id: 'SIG-5', type: 'FEAT', status: 'C', title: 'Rejected', close: { reason: 'rejected', by, at: '2026-09-04', proof: 'not wanted' } }),
  );
  put(
    base,
    '.planning/work/done/2026-09/SIG-6.md',
    item({ id: 'SIG-6', type: 'FEAT', status: 'C', title: 'Dup', close: { reason: 'dup', by, at: '2026-09-04', dup_of: 'SIG-2' } }),
  );
  put(
    base,
    '.planning/work/done/2026-09/SIG-123.md',
    item({ id: 'SIG-123', type: 'BUG', status: 'C', title: 'No commit', close: { reason: 'fixed', by, at: '2026-09-05', proof: 'fixed in v0.1.30' } }),
  );
  put(base, '.planning/archive/epics/M5.E1/README.md', '---\nclose:\n  at: 2026-09-06\n---\n# M5.E1\n');
  put(base, '.planning/archive/epics/M5.E1/M5.E1-PLAN.md', '# plan\n');
  put(
    base,
    '.planning/archive/epics/M5.E1/SIG-7.md',
    item({ id: 'SIG-7', type: 'FEAT', status: 'C', title: 'In an Epic', close: { reason: 'fixed', by, at: '2026-09-06', proof: 'legacy — not re-verified' } }),
  );
  // Generated v1 views, marker first, so regeneration may overwrite them.
  const marker = '<!-- generated by /sig:item — do not edit; edit the item files under .planning/work/ -->\n';
  for (const v of ['BUGS.md', 'BACKLOG.md', 'ISSUES-INBOX.md', 'OPEN-QUESTIONS.md', 'work/EPICS.md']) {
    put(base, `.planning/${v}`, `${marker}# v1 view\n`);
  }
  return base;
}

// A bare remote and a clone holding the v1 project, with `fixSha` on origin/main.
function v1Clone({ dirty = false } = {}) {
  const remote = join(root, 'remote.git');
  const work = join(root, 'work');
  g(root, 'init', '-q', '--bare', '-b', 'main', remote);
  mkdirSync(work);
  g(work, 'init', '-q', '-b', 'main');
  put(work, 'README.md', 'x\n');
  g(work, 'add', '-A');
  g(work, 'commit', '-q', '-m', 'fix');
  const fixSha = g(work, 'rev-parse', '--short=7', 'HEAD');
  v1Project(work, fixSha);
  g(work, 'add', '-A');
  g(work, 'commit', '-q', '-m', 'v1 store');
  g(work, 'remote', 'add', 'origin', remote);
  g(work, 'push', '-q', '-u', 'origin', 'main');
  g(work, 'remote', 'set-head', 'origin', 'main');
  if (dirty) put(work, 'scratch.txt', 'uncommitted\n');
  return { work, fixSha };
}

describe('migrateWorkStoreV2 — refusals', () => {
  it('refuses a project with no store (CONFIG), writing nothing', async () => {
    const base = join(root, 'p');
    put(base, '.planning/PROJECT.md', '# P\n');
    await expect(migrateWorkStoreV2(base, { outDir: join(root, 'out') })).rejects.toMatchObject({ code: 'CONFIG' });
    expect(existsSync(join(root, 'out'))).toBe(false);
  });

  it('refuses a v2 store (CONFIG: already migrated)', async () => {
    const base = join(root, 'p');
    put(base, '.planning/work/WORK.md', '---\nkey: SIG\nschema_version: 2\n---\n');
    await expect(migrateWorkStoreV2(base, { outDir: join(root, 'out') })).rejects.toThrow(/already .*v2|schema_version: 2/);
  });

  it('refuses an outDir inside the project', async () => {
    const base = v1Project(join(root, 'p'));
    await expect(migrateWorkStoreV2(base, { outDir: join(base, 'tmp-out') })).rejects.toThrow(/inside the project/);
    expect(existsSync(join(base, 'tmp-out'))).toBe(false);
  });

  it('refuses an outDir that already holds a .planning (never overwrites one)', async () => {
    const base = v1Project(join(root, 'p'));
    put(root, 'out/.planning/x.md', 'y\n');
    await expect(migrateWorkStoreV2(base, { outDir: join(root, 'out') })).rejects.toThrow(/already holds/);
  });
});

describe('migrateWorkStoreV2 — dry run builds aside, verified (AC8.1)', () => {
  it('writes nothing in the source project', async () => {
    const base = v1Project(join(root, 'p'));
    const before = snapshotTree(base);
    await migrateWorkStoreV2(base, { outDir: join(root, 'out'), now: NOW });
    expect(snapshotTree(base)).toEqual(before);
  });

  it('builds a v2 project in outDir: records + bodies, WORK.md v2, views, manifest.json; checkRecords is clean', async () => {
    const base = v1Project(join(root, 'p'));
    const out = join(root, 'out');
    const res = await migrateWorkStoreV2(base, { outDir: out, now: NOW });
    expect(res.mode).toBe('dry-run');
    expect(res.outDir).toBe(out);
    expect(storeVersion(out)).toBe(2);
    expect(readFileSync(join(out, '.planning/work/WORK.md'), 'utf-8')).toMatch(/^---\nkey: SIG\nschema_version: 2\n---\n/);
    for (const id of ['SIG-1', 'SIG-2', 'SIG-7', 'SIG-123']) {
      expect(existsSync(join(out, recordPath(id)))).toBe(true);
      expect(existsSync(join(out, recordPath(id).replace(/\.json$/, '.md')))).toBe(true);
    }
    const listed = listRecords(out);
    expect(listed.broken).toEqual([]);
    expect(listed.records.map((r) => r.id)).toEqual(['SIG-1', 'SIG-2', 'SIG-3', 'SIG-4', 'SIG-5', 'SIG-6', 'SIG-7', 'SIG-123']);
    expect(checkRecords(out)).toEqual([]);
    expect(readFileSync(join(out, '.planning/BUGS.md'), 'utf-8')).toMatch(/SIG-2/);
    const manifest = JSON.parse(readFileSync(join(out, 'manifest.json'), 'utf-8'));
    expect(manifest).toEqual(res.manifest);
  });

  it('relocates the v1 item files in the built project, keeping their paths; Epic documents stay', async () => {
    const base = v1Project(join(root, 'p'));
    const out = join(root, 'out');
    await migrateWorkStoreV2(base, { outDir: out, now: NOW });
    const reloc = join(out, '.planning/archive/pre-work-store-v2');
    expect(existsSync(join(reloc, 'work/inbox/SIG-1.md'))).toBe(true);
    expect(existsSync(join(reloc, 'archive/epics/M5.E1/SIG-7.md'))).toBe(true);
    expect(existsSync(join(out, '.planning/work/inbox/SIG-1.md'))).toBe(false);
    expect(existsSync(join(out, '.planning/archive/epics/M5.E1/SIG-7.md'))).toBe(false);
    expect(existsSync(join(out, '.planning/archive/epics/M5.E1/README.md'))).toBe(true);
    expect(existsSync(join(out, '.planning/archive/epics/M5.E1/M5.E1-PLAN.md'))).toBe(true);
    expect(findDuplicateIds(out)).toEqual([]);
  });

  it('removes the v1 status folders it emptied, never a file: a folder still holding one stays', async () => {
    const base = v1Project(join(root, 'p'));
    put(base, '.planning/work/backlog/notes.txt', 'not an item\n');
    const out = join(root, 'out');
    await migrateWorkStoreV2(base, { outDir: out, now: NOW });
    expect(existsSync(join(out, '.planning/work/inbox'))).toBe(false);
    expect(existsSync(join(out, '.planning/work/done'))).toBe(false);
    expect(readFileSync(join(out, '.planning/work/backlog/notes.txt'), 'utf-8')).toBe('not an item\n');
    // the Epic folder that held an item keeps its documents
    expect(existsSync(join(out, '.planning/archive/epics/M5.E1/README.md'))).toBe(true);
    // and the dry run leaves the source project alone
    expect(existsSync(join(base, '.planning/work/inbox/SIG-1.md'))).toBe(true);
  });

  it('rewrites WORK.md\'s body to describe records, keeping the frontmatter', async () => {
    const base = v1Project(join(root, 'p'));
    const out = join(root, 'out');
    await migrateWorkStoreV2(base, { outDir: out, now: NOW });
    const text = readFileSync(join(out, '.planning/work/WORK.md'), 'utf-8');
    expect(text).toMatch(/^---\nkey: SIG\nschema_version: 2\n---\n\n# Work store\n/);
    expect(text).toContain('.planning/work/items/NN/SIG-n.json');
    expect(text).toContain('`/sig:item`');
    expect(text).toContain('.planning/archive/pre-work-store-v2/');
    expect(text).not.toContain('v1 body text');
  });

  it('the manifest accounts for every v1 file, close form and body change, with zero errors', async () => {
    const base = v1Project(join(root, 'p'));
    const { manifest } = await migrateWorkStoreV2(base, { outDir: join(root, 'out'), now: NOW });
    expect(manifest.verification.errors).toEqual([]);
    expect(manifest.summary).toMatchObject({ v1Files: 8, records: 8, errors: 0, legacyCloses: 3 });
    expect(manifest.summary.closeForms).toEqual({ legacy: 2, 'legacy-no-commit': 1, close_requested: 1, direct: 1, dup: 1 });
    expect(manifest.nonLegacyCloses).toEqual([
      { id: 'SIG-4', form: 'close_requested', proof: expect.stringMatching(/^[0-9a-f]{7}$/) },
      { id: 'SIG-5', form: 'direct', reason: 'rejected' },
      { id: 'SIG-6', form: 'dup', dup_of: 'SIG-2' },
      { id: 'SIG-123', form: 'legacy-no-commit', reason: 'fixed' },
    ]);
    const sig2 = manifest.items.find((m) => m.id === 'SIG-2');
    expect(sig2.cellsRemoved.map((c) => c.cell)).toEqual(['id', 'status', 'priority']);
    expect(sig2.statusLinesRemoved).toHaveLength(1);
    expect(sig2.linksRewritten).toEqual([{ line: 1, from: '../../PROJECT.md', to: '../../../PROJECT.md' }]);
    expect(manifest.items.every((m) => m.relocatedTo.startsWith('.planning/archive/pre-work-store-v2/'))).toBe(true);
  });

  it('records the probe: which close requests confirmCloses would confirm against origin/<default>', async () => {
    const { work, fixSha } = v1Clone();
    const { manifest } = await migrateWorkStoreV2(work, { outDir: join(root, 'out'), now: NOW });
    expect(manifest.closes.requested).toEqual(['SIG-4']);
    expect(manifest.closes.probe).toMatchObject({
      ref: 'refs/remotes/origin/main',
      sha: expect.stringMatching(/^[0-9a-f]{40}$/),
      confirmable: ['SIG-4'],
      stillClosing: [],
    });
    expect(fixSha).toMatch(/^[0-9a-f]{7}$/);
    expect(manifest.closes.confirmed).toBeNull(); // dry run: nothing confirmed
  });

  it('the probe outside a git repo leaves every request closing, with the reason', async () => {
    const base = v1Project(join(root, 'p'));
    const { manifest } = await migrateWorkStoreV2(base, { outDir: join(root, 'out'), now: NOW });
    expect(manifest.closes.probe.confirmable).toEqual([]);
    expect(manifest.closes.probe.stillClosing).toEqual([{ id: 'SIG-4', reason: 'not-a-repo' }]);
  });

  it('an item that does not convert fails the run: nothing is built, the error is named', async () => {
    const base = v1Project(join(root, 'p'));
    put(base, '.planning/work/backlog/SIG-9.md', item({ id: 'SIG-9', type: 'FEAT', status: 'C', title: 'wrong folder' }));
    await expect(migrateWorkStoreV2(base, { outDir: join(root, 'out'), now: NOW })).rejects.toThrow(/SIG-9/);
    expect(existsSync(join(root, 'out', '.planning'))).toBe(false);
  });
});

describe('verifyConversion — the manifest check bites', () => {
  const texts = (base) => convertStore(base);

  it('passes on a clean conversion', () => {
    const base = v1Project(join(root, 'p'));
    expect(verifyConversion(texts(base)).errors).toEqual([]);
  });

  it('a v1 field neither mapped nor dropped is an error', () => {
    const base = v1Project(join(root, 'p'));
    const results = texts(base);
    results[1].manifest.fieldsMapped = results[1].manifest.fieldsMapped.filter((f) => f.from !== 'title');
    expect(verifyConversion(results).errors.join('\n')).toMatch(/SIG-2.*title.*neither mapped nor dropped/);
  });

  it('a link that no longer resolves to the same target is an error', () => {
    const base = v1Project(join(root, 'p'));
    const results = texts(base);
    results[1].manifest.linksRewritten[0].to = '../PROJECT.md';
    expect(verifyConversion(results).errors.join('\n')).toMatch(/SIG-2.*link/);
  });

  it('with exists: a link that reached a file from the v1 folder and does not from the new body is an error', () => {
    const base = v1Project(join(root, 'p'));
    const results = texts(base);
    const exists = (p) => existsSync(join(base, '.planning', p));
    expect(verifyConversion(results, { exists }).errors).toEqual([]);
    results[1].body = results[1].body.replace('../../../PROJECT.md', '../PROJECT.md');
    expect(verifyConversion(results, { exists }).errors.join('\n')).toMatch(/SIG-2.*link to PROJECT\.md resolved from the v1 file/);
  });

  it('a removed cell or status line still in the body is an error', () => {
    const base = v1Project(join(root, 'p'));
    const results = texts(base);
    results[1].body = `**Status:** confirmed\n${results[1].body}`;
    expect(verifyConversion(results).errors.join('\n')).toMatch(/SIG-2.*status line/);
  });

  it('two files with one ID is an error', () => {
    const base = v1Project(join(root, 'p'));
    put(base, '.planning/work/done/2026-10/SIG-1.md', item({ id: 'SIG-1', type: 'NEW', status: 'C', title: 'x', close: { reason: 'rejected', by, at: '2026-10-01', proof: 'p' } }));
    expect(verifyConversion(texts(base)).errors.join('\n')).toMatch(/SIG-1.*2 files/);
  });
});

describe('migrateWorkStoreV2 — apply (temp git repos only)', () => {
  it('refuses a dirty working tree, changing nothing', async () => {
    const { work } = v1Clone({ dirty: true });
    const before = snapshotTree(join(work, '.planning'));
    await expect(migrateWorkStoreV2(work, { apply: true, outDir: join(root, 'out'), now: NOW })).rejects.toThrow(/dirty|uncommitted/);
    expect(snapshotTree(join(work, '.planning'))).toEqual(before);
    expect(storeVersion(work)).toBe(1);
  });

  it('refuses outside a git repository', async () => {
    const base = v1Project(join(root, 'p'));
    await expect(migrateWorkStoreV2(base, { apply: true, outDir: join(root, 'out'), now: NOW })).rejects.toThrow(/git/);
    expect(storeVersion(base)).toBe(1);
  });

  it('writes the records, sets schema_version 2, relocates item files only, confirms the close, regenerates the views', async () => {
    const { work } = v1Clone();
    const res = await migrateWorkStoreV2(work, { apply: true, outDir: join(root, 'out'), now: NOW });
    expect(res.mode).toBe('apply');
    expect(storeVersion(work)).toBe(2);
    // t7.3 prep: the body is rewritten to describe records, not status folders.
    const workMd = readFileSync(join(work, '.planning/work/WORK.md'), 'utf-8');
    expect(workMd).toMatch(/^---\nkey: SIG\nschema_version: 2\n---\n/);
    expect(workMd).not.toMatch(/v1 body text/);
    expect(workMd).toContain('.planning/work/items/NN/SIG-n.json');
    expect(workMd).not.toMatch(/`inbox\/`|`backlog\/`|`done\/YYYY-MM\/`/);
    // relocated, never deleted; the Epic folder and its documents stay
    expect(existsSync(join(work, '.planning/archive/pre-work-store-v2/work/done/2026-09/SIG-4.md'))).toBe(true);
    expect(existsSync(join(work, '.planning/archive/pre-work-store-v2/archive/epics/M5.E1/SIG-7.md'))).toBe(true);
    expect(existsSync(join(work, '.planning/archive/epics/M5.E1/README.md'))).toBe(true);
    expect(existsSync(join(work, '.planning/archive/epics/M5.E1/SIG-7.md'))).toBe(false);
    // confirmCloses ran: SIG-4's commit is on origin/main
    expect(res.manifest.closes.confirmed).toEqual(['SIG-4']);
    const sig4 = listRecords(work).records.find((r) => r.id === 'SIG-4');
    expect(sig4.status).toBe('C');
    expect(sig4.record.events.at(-2).type).toBe('close_requested');
    expect(sig4.record.events.at(-1)).toMatchObject({ type: 'closed', by: 'confirmCloses', reason: 'fixed' });
    expect(checkRecords(work)).toEqual([]);
    expect(findDuplicateIds(work)).toEqual([]);
    // the manifest is written aside, and a copy goes into the project beside
    // the relocated v1 files (t7.3 prep) — committed with the cutover, the
    // record of what confirmCloses confirmed. Final: written after confirming.
    expect(existsSync(join(root, 'out', 'manifest.json'))).toBe(true);
    expect(existsSync(join(work, 'manifest.json'))).toBe(false);
    const kept = readFileSync(join(work, '.planning/archive/pre-work-store-v2/MANIFEST.json'), 'utf-8');
    expect(kept).toBe(readFileSync(join(root, 'out', 'manifest.json'), 'utf-8'));
    expect(JSON.parse(kept).closes.confirmed).toEqual(['SIG-4']);
    // the emptied v1 status folders are removed (rmdir only); Epic folders stay
    for (const gone of ['work/inbox', 'work/backlog', 'work/done']) expect(existsSync(join(work, '.planning', gone)), gone).toBe(false);
    expect(existsSync(join(work, '.planning/archive/epics/M5.E1'))).toBe(true);
  });

  it('apply then a second run refuses (already v2)', async () => {
    const { work } = v1Clone();
    await migrateWorkStoreV2(work, { apply: true, outDir: join(root, 'out'), now: NOW });
    g(work, 'add', '-A');
    g(work, 'commit', '-q', '-m', 'cutover');
    await expect(migrateWorkStoreV2(work, { apply: true, outDir: join(root, 'out2'), now: NOW })).rejects.toMatchObject({ code: 'CONFIG' });
  });
});
