// M6.E13 REVIEW I2 — the v1 → v2 migration never writes, renames or copies
// through a link, converts the store as it is under the lock, and tells the
// user how to recover when --apply fails part-way.
//
// Before this fix, a committed `.planning/work/items` link made even the
// default dry run write records outside the project (the copy kept the link,
// and the build aside wrote through it), and a linked `.planning/archive`
// made --apply move v1 files out of the repository.
//
// Attack fixtures live under mkdtemp only; --apply runs only in temp repos.

import { describe, it, expect, beforeEach, afterEach } from 'vitest';
import { execFileSync, spawnSync } from 'node:child_process';
import { existsSync, mkdirSync, mkdtempSync, readdirSync, realpathSync, rmSync, symlinkSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { tmpdir } from 'node:os';

import { migrateWorkStoreV2 } from '../plugin/tools/lib/work-migrate-v2.js';
import { stringifyItem } from '../plugin/tools/lib/work-item.js';
import { storeVersion } from '../plugin/tools/lib/work-records.js';
import { snapshotTree } from './helpers/write-inventory.js';

const AT = '2026-09-01T00:00:00.000Z';
const NOW = '2026-10-04T12:00:00.000Z';
const by = 'b';
const MARKER = '<!-- generated by /sig:item — do not edit; edit the item files under .planning/work/ -->\n';

function g(cwd, ...args) {
  const r = spawnSync('git', ['-c', 'commit.gpgsign=false', '-c', 'user.email=t@t.co', '-c', 'user.name=T', ...args], {
    cwd,
    encoding: 'utf8',
  });
  if (r.status !== 0) throw new Error(`git ${args.join(' ')}: ${r.stderr}`);
  return r.stdout.trim();
}

function put(base, rel, content) {
  const p = join(base, rel);
  mkdirSync(dirname(p), { recursive: true });
  writeFileSync(p, content);
}

const item = (fields, body = 'Body.\n') => stringifyItem({ created: { at: AT, by }, ...fields }, body);

// A small v1 store: two open items and generated v1 views.
function v1Project(base) {
  put(base, '.planning/work/WORK.md', '---\nkey: SIG\nschema_version: 1\n---\n\n# Work store\n');
  put(base, '.planning/work/inbox/SIG-1.md', item({ id: 'SIG-1', type: 'NEW', status: 'N', title: 'Raw capture' }));
  put(base, '.planning/work/backlog/SIG-2.md', item({ id: 'SIG-2', type: 'BUG', status: 'T', title: 'A bug' }));
  for (const v of ['BUGS.md', 'BACKLOG.md', 'ISSUES-INBOX.md', 'OPEN-QUESTIONS.md', 'work/EPICS.md']) {
    put(base, `.planning/${v}`, `${MARKER}# v1 view\n`);
  }
  return base;
}

function commitAll(work) {
  g(work, 'add', '-A');
  g(work, 'commit', '-q', '-m', 'v1 store');
}

let root;
let outside;
let work;
beforeEach(() => {
  root = realpathSync(mkdtempSync(join(tmpdir(), 'sig-migrate-confine-')));
  outside = realpathSync(mkdtempSync(join(tmpdir(), 'sig-migrate-escape-')));
  work = join(root, 'work');
  mkdirSync(work);
  g(work, 'init', '-q', '-b', 'main');
  v1Project(work);
});
afterEach(() => {
  rmSync(root, { recursive: true, force: true });
  rmSync(outside, { recursive: true, force: true });
});

describe('migrateWorkStoreV2 — links on the write path are refused before anything is written (REVIEW I2)', () => {
  it('dry run: a symlinked .planning/work/items is refused, and nothing is written outside the project or in outDir', async () => {
    symlinkSync(outside, join(work, '.planning/work/items'));
    const out = join(root, 'out');
    await expect(migrateWorkStoreV2(work, { outDir: out, now: NOW })).rejects.toMatchObject({
      code: 'CONFLICT',
      message: expect.stringMatching(/\.planning\/work\/items.*symbolic link/s),
    });
    expect(readdirSync(outside)).toEqual([]);
    expect(existsSync(join(out, '.planning'))).toBe(false);
  });

  it('apply: a symlinked .planning/archive is refused before any v1 file is moved', async () => {
    symlinkSync(outside, join(work, '.planning/archive'));
    commitAll(work);
    const before = snapshotTree(join(work, '.planning'));
    await expect(migrateWorkStoreV2(work, { apply: true, outDir: join(root, 'out'), now: NOW })).rejects.toMatchObject({
      code: 'CONFLICT',
      message: expect.stringMatching(/\.planning\/archive.*symbolic link/s),
    });
    expect(readdirSync(outside)).toEqual([]);
    expect(snapshotTree(join(work, '.planning'))).toEqual(before);
    expect(existsSync(join(work, '.planning/work/inbox/SIG-1.md'))).toBe(true);
    expect(storeVersion(work)).toBe(1);
  });

  it('a symlinked v1 status folder is refused (its files would be moved in from outside)', async () => {
    rmSync(join(work, '.planning/work/backlog'), { recursive: true });
    put(outside, 'SIG-2.md', item({ id: 'SIG-2', type: 'BUG', status: 'T', title: 'outside' }));
    symlinkSync(outside, join(work, '.planning/work/backlog'));
    await expect(migrateWorkStoreV2(work, { outDir: join(root, 'out'), now: NOW })).rejects.toMatchObject({ code: 'CONFLICT' });
    expect(readdirSync(outside)).toEqual(['SIG-2.md']);
  });

  it('an outDir that is itself a symlink is refused', async () => {
    const link = join(root, 'out-link');
    symlinkSync(outside, link);
    await expect(migrateWorkStoreV2(work, { outDir: link, now: NOW })).rejects.toMatchObject({
      code: 'CONFIG',
      message: expect.stringMatching(/out-link.*symbolic link/s),
    });
    expect(readdirSync(outside)).toEqual([]);
  });
});

describe('migrateWorkStoreV2 — apply converts the store as it is under the lock (REVIEW I2)', () => {
  it('a v1 item added between the conversion and the lock refuses the apply, naming it — never silently skipped', async () => {
    commitAll(work);
    let planted = false;
    // headSha runs `git rev-parse HEAD` after the conversion and before the
    // lock: a concurrent capture lands in that window.
    const execFn = (cmd, args, o) => {
      if (!planted && args[0] === 'rev-parse' && args[1] === 'HEAD') {
        planted = true;
        put(work, '.planning/work/inbox/SIG-9.md', item({ id: 'SIG-9', type: 'NEW', status: 'N', title: 'late' }));
      }
      return execFileSync(cmd, args, o);
    };
    await expect(migrateWorkStoreV2(work, { apply: true, outDir: join(root, 'out'), now: NOW, execFn })).rejects.toMatchObject({
      code: 'CONFLICT',
      message: expect.stringMatching(/SIG-9/),
    });
    expect(planted).toBe(true);
    expect(storeVersion(work)).toBe(1);
    expect(existsSync(join(work, '.planning/work/inbox/SIG-1.md'))).toBe(true);
    expect(existsSync(join(work, '.planning/work/items'))).toBe(false);
  });

  it('a v1 item edited between the conversion and the lock refuses the apply too', async () => {
    commitAll(work);
    let planted = false;
    const execFn = (cmd, args, o) => {
      if (!planted && args[0] === 'rev-parse' && args[1] === 'HEAD') {
        planted = true;
        put(work, '.planning/work/inbox/SIG-1.md', item({ id: 'SIG-1', type: 'NEW', status: 'N', title: 'edited meanwhile' }));
      }
      return execFileSync(cmd, args, o);
    };
    await expect(migrateWorkStoreV2(work, { apply: true, outDir: join(root, 'out'), now: NOW, execFn })).rejects.toMatchObject({
      code: 'CONFLICT',
      message: expect.stringMatching(/SIG-1/),
    });
    expect(storeVersion(work)).toBe(1);
  });
});

describe('migrateWorkStoreV2 — an apply that fails part-way names the recovery (REVIEW I2)', () => {
  it('prints the git commands, and running them restores the tree exactly', async () => {
    commitAll(work);
    const workReal = realpathSync(work);
    // Fail the project's own record write for SIG-2 (the aside build passes).
    const renameFn = async (from, to) => {
      if (to.startsWith(workReal) && to.endsWith('SIG-2.json')) throw Object.assign(new Error('disk on fire'), { code: 'EIO' });
      const { rename } = await import('node:fs/promises');
      return rename(from, to);
    };
    let err;
    try {
      await migrateWorkStoreV2(work, { apply: true, outDir: join(root, 'out'), now: NOW, renameFn });
    } catch (e) {
      err = e;
    }
    expect(err).toBeDefined();
    expect(err.message).toMatch(/disk on fire/);
    expect(err.message).toContain('git checkout -- .planning && git clean -fd .planning');
    // The project was changed part-way (SIG-1's record, the relocation) ...
    expect(g(work, 'status', '--porcelain')).not.toBe('');
    // A narrower clean (only work/items) is not enough: the relocated v1
    // copies stay behind, untracked.
    execFileSync('sh', ['-c', 'git checkout -- .planning && git clean -fd .planning/work/items'], { cwd: work, stdio: 'ignore' });
    expect(g(work, 'status', '--porcelain')).toMatch(/\?\? \.planning\/archive\//);
    // ... and the printed commands put it back.
    execFileSync('sh', ['-c', 'git checkout -- .planning && git clean -fd .planning'], { cwd: work, stdio: 'ignore' });
    expect(g(work, 'status', '--porcelain')).toBe('');
    expect(storeVersion(work)).toBe(1);
  });

  it('a refusal before the first project write does not tell the user to run git checkout', async () => {
    commitAll(work);
    put(work, 'scratch.txt', 'dirty\n');
    await expect(migrateWorkStoreV2(work, { apply: true, outDir: join(root, 'out'), now: NOW }))
      .rejects.toSatisfy((e) => /dirty/.test(e.message) && !/git checkout/.test(e.message));
  });
});

// REVIEW pass 2: the recovery is git's, so it only holds for files git has.
describe('migrateWorkStoreV2 — --apply needs every v1 file tracked, and its recovery works from a subdirectory', () => {
  it('a git-ignored v1 item refuses the apply under the lock, naming it, before anything is written', async () => {
    put(work, '.gitignore', '.planning/work/backlog/SIG-2.md\n');
    commitAll(work);
    expect(g(work, 'status', '--porcelain')).toBe(''); // the clean-tree check cannot see it
    const before = snapshotTree(join(work, '.planning'));
    await expect(migrateWorkStoreV2(work, { apply: true, outDir: join(root, 'out'), now: NOW })).rejects.toSatisfy(
      (e) => e.code === 'CONFIG' && /SIG-2\.md/.test(e.message) && /not tracked/.test(e.message) && !/git checkout/.test(e.message),
    );
    expect(snapshotTree(join(work, '.planning'))).toEqual(before);
    expect(storeVersion(work)).toBe(1);
  });

  it('a project in a subdirectory of its repository: the printed recovery, run from the project, restores it', async () => {
    const repo = join(root, 'repo');
    const proj = join(repo, 'apps', 'proj');
    mkdirSync(proj, { recursive: true });
    g(repo, 'init', '-q', '-b', 'main');
    v1Project(proj);
    put(repo, 'README.md', 'repo\n');
    commitAll(repo);
    const projReal = realpathSync(proj);
    const renameFn = async (from, to) => {
      if (to.startsWith(projReal) && to.endsWith('SIG-2.json')) throw Object.assign(new Error('disk on fire'), { code: 'EIO' });
      const { rename } = await import('node:fs/promises');
      return rename(from, to);
    };
    const err = await migrateWorkStoreV2(proj, { apply: true, outDir: join(root, 'out'), now: NOW, renameFn }).catch((e) => e);
    expect(err.message).toMatch(/disk on fire/);
    expect(err.message).toMatch(/project directory/);
    expect(err.message).not.toMatch(/exactly/);
    expect(g(repo, 'status', '--porcelain')).not.toBe('');
    execFileSync('sh', ['-c', err.recovery], { cwd: proj, stdio: 'ignore' });
    expect(g(repo, 'status', '--porcelain')).toBe('');
    expect(storeVersion(proj)).toBe(1);
  });
});
