// The generated-file marker (M6.E11, D-M6E11-25, D-M6E11-28).
//
// With the store on, the four lists are regenerated from item files and carry
// this marker as their first line. A leaf module — no imports from `lib/` —
// because `atomic-write.js` checks it on every write and must stay free of
// the store's import graph.
//
// The check is the FIRST LINE, EXACTLY (a trailing `\r` and one leading
// UTF-8 BOM aside), never a substring: Signal's own docs quote the marker, and
// a substring check would refuse to write them. The BOM is allowed because an
// editor that saves one would otherwise turn the guard off (REVIEW, pass 1).

import { closeSync, openSync, readSync } from 'node:fs';

/** The exact first line of every generated file. */
export const GENERATED_MARKER = '<!-- generated by /sig:item — do not edit; edit the item files under .planning/work/ -->';

/** How much of a file the check reads — the marker is well under this. */
export const MARKER_READ_BYTES = 200;

/**
 * Does this text start with the marker line?
 * @param {string|null|undefined} text
 * @returns {boolean}
 */
export function isGeneratedText(text) {
  if (typeof text !== 'string') return false;
  const nl = text.indexOf('\n');
  const first = nl === -1 ? text : text.slice(0, nl);
  return first.replace(/^\uFEFF/, '').replace(/\r$/, '') === GENERATED_MARKER;
}

/**
 * Is the file at `path` a generated file? Reads at most 200 bytes. A missing
 * or unreadable file is not generated.
 * @param {string} path
 * @returns {boolean}
 */
export function isGeneratedFile(path) {
  let fd;
  try {
    fd = openSync(path, 'r');
  } catch {
    return false;
  }
  try {
    const buf = Buffer.alloc(MARKER_READ_BYTES);
    const n = readSync(fd, buf, 0, MARKER_READ_BYTES, 0);
    const text = buf.toString('utf-8', 0, n);
    // No newline inside a full read: the first line is longer than the marker.
    if (n === MARKER_READ_BYTES && !text.includes('\n')) return false;
    return isGeneratedText(text);
  } catch {
    return false;
  } finally {
    closeSync(fd);
  }
}
